version: '3.8'

services:
  etcd:
    image: bitnami/etcd:3.5
    container_name: config-cli-etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://127.0.0.1:2379
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - etcd_data:/bitnami/etcd

volumes:
  etcd_data:
