name: audio_editor
description: 桌面音频剪辑工具 (Flutter + FFmpeg + Dart FFI)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  ffi: ^2.1.2
  path: ^1.9.0
  path_provider: ^2.1.1
  file_picker: ^6.1.1
  audioplayers: ^5.2.1
  provider: ^6.1.1
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
