local const = {}

const.WORLD_W = 1920
const.WORLD_H = 1440

const.PLAYER_RADIUS = 14
const.PLAYER_SPEED = 220
const.PLAYER_MAX_HP = 100

const.FLASH_RANGE = 360
const.FLASH_HALF_ANGLE = math.rad(28)
const.AMBIENT = 0.08

const.ENEMY_RADIUS = 14
const.ENEMY_SPEED = 95
const.ENEMY_DAMAGE = 14
const.ENEMY_ATTACK_COOLDOWN = 0.8
const.ENEMY_SPAWN_DIST_MIN = 420
const.ENEMY_SPAWN_DIST_MAX = 700
const.ENEMY_INITIAL_COUNT = 10
const.ENEMY_MAX_COUNT = 18
const.ENEMY_SPAWN_INTERVAL = 4.0

const.BULLET_SPEED = 900
const.BULLET_RADIUS = 3
const.BULLET_MAX_LIFE = 1.2

const.PISTOL_DAMAGE = 26
const.PISTOL_FIRE_INTERVAL = 0.22
const.PISTOL_AMMO_MAX = 60
const.PISTOL_MAG_SIZE = 12
const.PISTOL_RELOAD_TIME = 1.1
const.PISTOL_SPREAD = 0.02

const.SHOTGUN_DAMAGE = 12
const.SHOTGUN_PELLETS = 6
const.SHOTGUN_FIRE_INTERVAL = 0.7
const.SHOTGUN_AMMO_MAX = 24
const.SHOTGUN_MAG_SIZE = 6
const.SHOTGUN_RELOAD_TIME = 1.6
const.SHOTGUN_SPREAD = 0.22

return const
