connector.name=iceberg
iceberg.catalog.type=rest
iceberg.rest-catalog.uri=http://rest-catalog:8181
iceberg.rest-catalog.warehouse=s3://warehouse/
fs.native-s3.enabled=true
s3.endpoint=http://minio:9000
s3.path-style-access=true
s3.aws-access-key=minioadmin
s3.aws-secret-key=minioadmin
s3.region=us-east-1
iceberg.register-table-procedure.enabled=true
iceberg.delete_file.enabled=true
iceberg.position-delete.enabled=true
iceberg.equality-delete.enabled=true
iceberg.merge-on-read.enabled=true
