// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || amd64p32 || arm || arm64 || mips64le || mips64p32le || mipsle || ppc64le || riscv64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

//go:embed bpf_bpfel.o
var bpfBin []byte

type bpfProgramSpec struct {
	*ebpf.ProgramSpec
}

type bpfMapSpec struct {
	*ebpf.MapSpec
}

type bpfObjects struct {
	MirrorHttp *ebpf.Program `ebpf:"mirror_http"`
	Events     *ebpf.Map     `ebpf:"events"`
}

func (o *bpfObjects) Close() error {
	for _, item := range []interface{ io.Closer }{
		o.MirrorHttp,
		o.Events,
	} {
		if item != nil {
			if err := item.Close(); err != nil {
				return err
			}
		}
	}
	return nil
}

func loadBpfObjects(target interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(target, opts)
}

func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(bpfBin)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load BPF elf from memory: %w", err)
	}

	return spec, err
}
