apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mysql.yaml
  - redis.yaml
  - jaeger.yaml
  - scheduler.yaml
  - executor.yaml

namespace: task-scheduler

commonLabels:
  app: task-scheduler-system
