FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /consumer ./cmd/consumer

FROM alpine:3.19

WORKDIR /app
COPY --from=builder /consumer .

ENTRYPOINT ["./consumer"]
